// Code generated by "stringer -type=AType"; DO NOT EDIT

package jingo

import "fmt"

const _AType_name = "NoATypeB01LITINTFLCMPXBOXXNUMRATBITSB01SLITSINTSFLSCMPXSBOXSBTC2TVERBADVCONJASGNMARKSYMBCONWNAMELPAREDGERPARXDXZAVNCAVNANY"

var _AType_map = map[AType]string{
	0:          _AType_name[0:7],
	2:          _AType_name[7:10],
	4:          _AType_name[10:13],
	8:          _AType_name[13:16],
	16:         _AType_name[16:18],
	32:         _AType_name[18:22],
	64:         _AType_name[22:25],
	128:        _AType_name[25:29],
	256:        _AType_name[29:32],
	512:        _AType_name[32:35],
	1024:       _AType_name[35:39],
	2048:       _AType_name[39:43],
	4096:       _AType_name[43:47],
	8192:       _AType_name[47:50],
	16384:      _AType_name[50:55],
	32768:      _AType_name[55:59],
	65536:      _AType_name[59:62],
	131072:     _AType_name[62:65],
	262144:     _AType_name[65:69],
	524288:     _AType_name[69:72],
	1048576:    _AType_name[72:76],
	2097152:    _AType_name[76:80],
	4194304:    _AType_name[80:84],
	8388608:    _AType_name[84:88],
	16777216:   _AType_name[88:92],
	33554432:   _AType_name[92:96],
	67108864:   _AType_name[96:100],
	73400320:   _AType_name[100:104],
	134217728:  _AType_name[104:108],
	268435456:  _AType_name[108:110],
	536870912:  _AType_name[110:112],
	806354942:  _AType_name[112:115],
	807403518:  _AType_name[115:119],
	4294967295: _AType_name[119:122],
}

func (i AType) String() string {
	if str, ok := _AType_map[i]; ok {
		return str
	}
	return fmt.Sprintf("AType(%d)", i)
}
