// Code generated by "stringer -type=CSType"; DO NOT EDIT

package jingo

import "fmt"

const _CSType_name = "SSSXSASNSNBSNZS9SQSQQSZ"

var _CSType_index = [...]uint8{0, 2, 4, 6, 8, 11, 14, 16, 18, 21, 23}

func (i CSType) String() string {
	if i < 0 || i >= CSType(len(_CSType_index)-1) {
		return fmt.Sprintf("CSType(%d)", i)
	}
	return _CSType_name[_CSType_index[i]:_CSType_index[i+1]]
}
