// Code generated by "stringer -type=EffType"; DO NOT EDIT

package jingo

import "fmt"

const _EffType_name = "E0EIEN"

var _EffType_index = [...]uint8{0, 2, 4, 6}

func (i EffType) String() string {
	if i < 0 || i >= EffType(len(_EffType_index)-1) {
		return fmt.Sprintf("EffType(%d)", i)
	}
	return _EffType_name[_EffType_index[i]:_EffType_index[i+1]]
}
