// Code generated by "stringer -type=ESCType"; DO NOT EDIT

package jingo

import "fmt"

const _ESCType_name = "CESC1"

var _ESCType_index = [...]uint8{0, 5}

func (i ESCType) String() string {
	i -= 46
	if i < 0 || i >= ESCType(len(_ESCType_index)-1) {
		return fmt.Sprintf("ESCType(%d)", i+46)
	}
	return _ESCType_name[_ESCType_index[i]:_ESCType_index[i+1]]
}
